version: "3.8"
services:
  mongo:
    image: mongo
    container_name: pynk_database
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
